<?php
/**
 * Boardingv1registrationsOrganizationInformationOwnersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Boardingv1registrationsOrganizationInformationOwnersTest Class Doc Comment
 *
 * @category    Class */
// * @description Boardingv1registrationsOrganizationInformationOwners
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Boardingv1registrationsOrganizationInformationOwnersTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Boardingv1registrationsOrganizationInformationOwners"
     */
    public function testBoardingv1registrationsOrganizationInformationOwners()
    {
    }

    /**
     * Test attribute "firstName"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "middleName"
     */
    public function testPropertyMiddleName()
    {
    }

    /**
     * Test attribute "lastName"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "birthDate"
     */
    public function testPropertyBirthDate()
    {
    }

    /**
     * Test attribute "isPrimary"
     */
    public function testPropertyIsPrimary()
    {
    }

    /**
     * Test attribute "ssn"
     */
    public function testPropertySsn()
    {
    }

    /**
     * Test attribute "passportNumber"
     */
    public function testPropertyPassportNumber()
    {
    }

    /**
     * Test attribute "passportCountry"
     */
    public function testPropertyPassportCountry()
    {
    }

    /**
     * Test attribute "jobTitle"
     */
    public function testPropertyJobTitle()
    {
    }

    /**
     * Test attribute "hasSignificantResponsability"
     */
    public function testPropertyHasSignificantResponsability()
    {
    }

    /**
     * Test attribute "ownershipPercentage"
     */
    public function testPropertyOwnershipPercentage()
    {
    }

    /**
     * Test attribute "phoneNumber"
     */
    public function testPropertyPhoneNumber()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }
}
