<?php
/**
 * CreateWebhookTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * CreateWebhookTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateWebhook
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateWebhookTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateWebhook"
     */
    public function testCreateWebhook()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "organizationId"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "productId"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "eventTypes"
     */
    public function testPropertyEventTypes()
    {
    }

    /**
     * Test attribute "webhookUrl"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "healthCheckUrl"
     */
    public function testPropertyHealthCheckUrl()
    {
    }

    /**
     * Test attribute "notificationScope"
     */
    public function testPropertyNotificationScope()
    {
    }

    /**
     * Test attribute "retryPolicy"
     */
    public function testPropertyRetryPolicy()
    {
    }

    /**
     * Test attribute "securityPolicy"
     */
    public function testPropertySecurityPolicy()
    {
    }
}
