<?php
/**
 * InlineResponse2005EmbeddedTotalsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * InlineResponse2005EmbeddedTotalsTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponse2005EmbeddedTotals
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2005EmbeddedTotalsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2005EmbeddedTotals"
     */
    public function testInlineResponse2005EmbeddedTotals()
    {
    }

    /**
     * Test attribute "acceptedRecords"
     */
    public function testPropertyAcceptedRecords()
    {
    }

    /**
     * Test attribute "rejectedRecords"
     */
    public function testPropertyRejectedRecords()
    {
    }

    /**
     * Test attribute "updatedRecords"
     */
    public function testPropertyUpdatedRecords()
    {
    }

    /**
     * Test attribute "caResponses"
     */
    public function testPropertyCaResponses()
    {
    }

    /**
     * Test attribute "caResponsesOmitted"
     */
    public function testPropertyCaResponsesOmitted()
    {
    }
}
