<?php
/**
 * Kmsegressv2keysasymKeyInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Kmsegressv2keysasymKeyInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Egress Asymmetric  Key Information Request
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Kmsegressv2keysasymKeyInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Kmsegressv2keysasymKeyInformation"
     */
    public function testKmsegressv2keysasymKeyInformation()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "tenant"
     */
    public function testPropertyTenant()
    {
    }

    /**
     * Test attribute "keyType"
     */
    public function testPropertyKeyType()
    {
    }

    /**
     * Test attribute "organizationId"
     */
    public function testPropertyOrganizationId()
    {
    }

    /**
     * Test attribute "pub"
     */
    public function testPropertyPub()
    {
    }

    /**
     * Test attribute "keyId"
     */
    public function testPropertyKeyId()
    {
    }

    /**
     * Test attribute "pvt"
     */
    public function testPropertyPvt()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "expiryDuration"
     */
    public function testPropertyExpiryDuration()
    {
    }
}
