<?php
/**
 * PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayoutsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayoutsTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayouts
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayoutsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayouts"
     */
    public function testPaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentPayouts()
    {
    }

    /**
     * Test attribute "reimbursementCode"
     */
    public function testPropertyReimbursementCode()
    {
    }

    /**
     * Test attribute "acquiringInstitutionId"
     */
    public function testPropertyAcquiringInstitutionId()
    {
    }

    /**
     * Test attribute "businessApplicationId"
     */
    public function testPropertyBusinessApplicationId()
    {
    }

    /**
     * Test attribute "financialInstitutionId"
     */
    public function testPropertyFinancialInstitutionId()
    {
    }

    /**
     * Test attribute "merchantAbaNumber"
     */
    public function testPropertyMerchantAbaNumber()
    {
    }

    /**
     * Test attribute "networkOrder"
     */
    public function testPropertyNetworkOrder()
    {
    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {
    }

    /**
     * Test attribute "merchantId"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "terminalId"
     */
    public function testPropertyTerminalId()
    {
    }
}
