<?php
/**
 * PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessorsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessorsTest Class Doc Comment
 *
 * @category    Class */
// * @description PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessors
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessorsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessors"
     */
    public function testPaymentProductsCardProcessingConfigurationInformationConfigurationsFeaturesCardNotPresentProcessors()
    {
    }

    /**
     * Test attribute "relaxAddressVerificationSystem"
     */
    public function testPropertyRelaxAddressVerificationSystem()
    {
    }

    /**
     * Test attribute "relaxAddressVerificationSystemAllowZipWithoutCountry"
     */
    public function testPropertyRelaxAddressVerificationSystemAllowZipWithoutCountry()
    {
    }

    /**
     * Test attribute "relaxAddressVerificationSystemAllowExpiredCard"
     */
    public function testPropertyRelaxAddressVerificationSystemAllowExpiredCard()
    {
    }

    /**
     * Test attribute "enableEmsTransactionRiskScore"
     */
    public function testPropertyEnableEmsTransactionRiskScore()
    {
    }

    /**
     * Test attribute "prestigiousPropertyIndicator"
     */
    public function testPropertyPrestigiousPropertyIndicator()
    {
    }

    /**
     * Test attribute "payouts"
     */
    public function testPropertyPayouts()
    {
    }
}
