<?php
/**
 * PtsV2PaymentsReversalsPost201ResponseReversalAmountDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PtsV2PaymentsReversalsPost201ResponseReversalAmountDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsReversalsPost201ResponseReversalAmountDetails
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsReversalsPost201ResponseReversalAmountDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsReversalsPost201ResponseReversalAmountDetails"
     */
    public function testPtsV2PaymentsReversalsPost201ResponseReversalAmountDetails()
    {
    }

    /**
     * Test attribute "reversedAmount"
     */
    public function testPropertyReversedAmount()
    {
    }

    /**
     * Test attribute "originalTransactionAmount"
     */
    public function testPropertyOriginalTransactionAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }
}
