<?php
/**
 * Ptsv2billingagreementsInstallmentInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Ptsv2billingagreementsInstallmentInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2billingagreementsInstallmentInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2billingagreementsInstallmentInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2billingagreementsInstallmentInformation"
     */
    public function testPtsv2billingagreementsInstallmentInformation()
    {
    }

    /**
     * Test attribute "alertPreference"
     */
    public function testPropertyAlertPreference()
    {
    }

    /**
     * Test attribute "firstInstallmentDate"
     */
    public function testPropertyFirstInstallmentDate()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }

    /**
     * Test attribute "lastInstallmentDate"
     */
    public function testPropertyLastInstallmentDate()
    {
    }

    /**
     * Test attribute "maxAmount"
     */
    public function testPropertyMaxAmount()
    {
    }

    /**
     * Test attribute "minAmount"
     */
    public function testPropertyMinAmount()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "preferredDay"
     */
    public function testPropertyPreferredDay()
    {
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
    }
}
