<?php
/**
 * Ptsv2paymentsidrefundsProcessingInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Ptsv2paymentsidrefundsProcessingInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentsidrefundsProcessingInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsidrefundsProcessingInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2paymentsidrefundsProcessingInformation"
     */
    public function testPtsv2paymentsidrefundsProcessingInformation()
    {
    }

    /**
     * Test attribute "actionList"
     */
    public function testPropertyActionList()
    {
    }

    /**
     * Test attribute "paymentSolution"
     */
    public function testPropertyPaymentSolution()
    {
    }

    /**
     * Test attribute "reconciliationId"
     */
    public function testPropertyReconciliationId()
    {
    }

    /**
     * Test attribute "linkId"
     */
    public function testPropertyLinkId()
    {
    }

    /**
     * Test attribute "reportGroup"
     */
    public function testPropertyReportGroup()
    {
    }

    /**
     * Test attribute "visaCheckoutId"
     */
    public function testPropertyVisaCheckoutId()
    {
    }

    /**
     * Test attribute "purchaseLevel"
     */
    public function testPropertyPurchaseLevel()
    {
    }

    /**
     * Test attribute "recurringOptions"
     */
    public function testPropertyRecurringOptions()
    {
    }

    /**
     * Test attribute "industryDataType"
     */
    public function testPropertyIndustryDataType()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "refundOptions"
     */
    public function testPropertyRefundOptions()
    {
    }
}
