<?php
/**
 * Ptsv2paymentsInstallmentInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Ptsv2paymentsInstallmentInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Ptsv2paymentsInstallmentInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Ptsv2paymentsInstallmentInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ptsv2paymentsInstallmentInformation"
     */
    public function testPtsv2paymentsInstallmentInformation()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "frequency"
     */
    public function testPropertyFrequency()
    {
    }

    /**
     * Test attribute "planType"
     */
    public function testPropertyPlanType()
    {
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
    }

    /**
     * Test attribute "totalAmount"
     */
    public function testPropertyTotalAmount()
    {
    }

    /**
     * Test attribute "totalCount"
     */
    public function testPropertyTotalCount()
    {
    }

    /**
     * Test attribute "firstInstallmentDate"
     */
    public function testPropertyFirstInstallmentDate()
    {
    }

    /**
     * Test attribute "invoiceData"
     */
    public function testPropertyInvoiceData()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "eligibilityInquiry"
     */
    public function testPropertyEligibilityInquiry()
    {
    }

    /**
     * Test attribute "gracePeriodDuration"
     */
    public function testPropertyGracePeriodDuration()
    {
    }

    /**
     * Test attribute "gracePeriodDurationType"
     */
    public function testPropertyGracePeriodDurationType()
    {
    }

    /**
     * Test attribute "firstInstallmentAmount"
     */
    public function testPropertyFirstInstallmentAmount()
    {
    }

    /**
     * Test attribute "validationIndicator"
     */
    public function testPropertyValidationIndicator()
    {
    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {
    }
}
