<?php
/**
 * PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponseTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse"
     */
    public function testPtsV2PaymentsPost201ResponseProcessorInformationConsumerAuthenticationResponse()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "codeRaw"
     */
    public function testPropertyCodeRaw()
    {
    }
}
