<?php
/**
 * PtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description PtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetails
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetailsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetails"
     */
    public function testPtsV2PaymentsPost201ResponseOrderInformationRewardPointsDetails()
    {
    }

    /**
     * Test attribute "pointsBeforeRedemption"
     */
    public function testPropertyPointsBeforeRedemption()
    {
    }

    /**
     * Test attribute "pointsValueBeforeRedemption"
     */
    public function testPropertyPointsValueBeforeRedemption()
    {
    }

    /**
     * Test attribute "pointsRedeemed"
     */
    public function testPropertyPointsRedeemed()
    {
    }

    /**
     * Test attribute "pointsValueRedeemed"
     */
    public function testPropertyPointsValueRedeemed()
    {
    }

    /**
     * Test attribute "pointsAfterRedemption"
     */
    public function testPropertyPointsAfterRedemption()
    {
    }

    /**
     * Test attribute "pointsValueAfterRedemption"
     */
    public function testPropertyPointsValueAfterRedemption()
    {
    }
}
