<?php
/**
 * PtsV2PaymentsPost201ResponseRiskInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * PtsV2PaymentsPost201ResponseRiskInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Contains the result of risk assessment.
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PtsV2PaymentsPost201ResponseRiskInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PtsV2PaymentsPost201ResponseRiskInformation"
     */
    public function testPtsV2PaymentsPost201ResponseRiskInformation()
    {
    }

    /**
     * Test attribute "profile"
     */
    public function testPropertyProfile()
    {
    }

    /**
     * Test attribute "rules"
     */
    public function testPropertyRules()
    {
    }

    /**
     * Test attribute "infoCodes"
     */
    public function testPropertyInfoCodes()
    {
    }

    /**
     * Test attribute "velocity"
     */
    public function testPropertyVelocity()
    {
    }

    /**
     * Test attribute "casePriority"
     */
    public function testPropertyCasePriority()
    {
    }

    /**
     * Test attribute "localTime"
     */
    public function testPropertyLocalTime()
    {
    }

    /**
     * Test attribute "score"
     */
    public function testPropertyScore()
    {
    }

    /**
     * Test attribute "ipAddress"
     */
    public function testPropertyIpAddress()
    {
    }

    /**
     * Test attribute "providers"
     */
    public function testPropertyProviders()
    {
    }

    /**
     * Test attribute "travel"
     */
    public function testPropertyTravel()
    {
    }
}
