<?php
/**
 * ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettingsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings"
     */
    public function testReportingV3ReportDefinitionsNameGet200ResponseDefaultSettings()
    {
    }

    /**
     * Test attribute "reportMimeType"
     */
    public function testPropertyReportMimeType()
    {
    }

    /**
     * Test attribute "reportFrequency"
     */
    public function testPropertyReportFrequency()
    {
    }

    /**
     * Test attribute "reportName"
     */
    public function testPropertyReportName()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "startTime"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "startDay"
     */
    public function testPropertyStartDay()
    {
    }

    /**
     * Test attribute "reportFilters"
     */
    public function testPropertyReportFilters()
    {
    }

    /**
     * Test attribute "reportPreferences"
     */
    public function testPropertyReportPreferences()
    {
    }
}
