<?php
/**
 * Riskv1exportcomplianceinquiriesOrderInformationLineItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Riskv1exportcomplianceinquiriesOrderInformationLineItemsTest Class Doc Comment
 *
 * @category    Class */
// * @description Riskv1exportcomplianceinquiriesOrderInformationLineItems
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Riskv1exportcomplianceinquiriesOrderInformationLineItemsTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Riskv1exportcomplianceinquiriesOrderInformationLineItems"
     */
    public function testRiskv1exportcomplianceinquiriesOrderInformationLineItems()
    {
    }

    /**
     * Test attribute "unitPrice"
     */
    public function testPropertyUnitPrice()
    {
    }

    /**
     * Test attribute "allowedExportCountries"
     */
    public function testPropertyAllowedExportCountries()
    {
    }

    /**
     * Test attribute "restrictedExportCountries"
     */
    public function testPropertyRestrictedExportCountries()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "productSKU"
     */
    public function testPropertyProductSKU()
    {
    }

    /**
     * Test attribute "productRisk"
     */
    public function testPropertyProductRisk()
    {
    }

    /**
     * Test attribute "productName"
     */
    public function testPropertyProductName()
    {
    }

    /**
     * Test attribute "productCode"
     */
    public function testPropertyProductCode()
    {
    }
}
