<?php
/**
 * Riskv1authenticationresultsConsumerAuthenticationInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Riskv1authenticationresultsConsumerAuthenticationInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Riskv1authenticationresultsConsumerAuthenticationInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Riskv1authenticationresultsConsumerAuthenticationInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Riskv1authenticationresultsConsumerAuthenticationInformation"
     */
    public function testRiskv1authenticationresultsConsumerAuthenticationInformation()
    {
    }

    /**
     * Test attribute "authenticationTransactionId"
     */
    public function testPropertyAuthenticationTransactionId()
    {
    }

    /**
     * Test attribute "authenticationTransactionContext"
     */
    public function testPropertyAuthenticationTransactionContext()
    {
    }

    /**
     * Test attribute "otpToken"
     */
    public function testPropertyOtpToken()
    {
    }

    /**
     * Test attribute "authenticationType"
     */
    public function testPropertyAuthenticationType()
    {
    }

    /**
     * Test attribute "effectiveAuthenticationType"
     */
    public function testPropertyEffectiveAuthenticationType()
    {
    }

    /**
     * Test attribute "responseAccessToken"
     */
    public function testPropertyResponseAccessToken()
    {
    }

    /**
     * Test attribute "signedParesStatusReason"
     */
    public function testPropertySignedParesStatusReason()
    {
    }

    /**
     * Test attribute "signedPares"
     */
    public function testPropertySignedPares()
    {
    }

    /**
     * Test attribute "whiteListStatus"
     */
    public function testPropertyWhiteListStatus()
    {
    }

    /**
     * Test attribute "credentialEncrypted"
     */
    public function testPropertyCredentialEncrypted()
    {
    }
}
