<?php
/**
 * Riskv1authenticationresultsPaymentInformationFluidDataTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Riskv1authenticationresultsPaymentInformationFluidDataTest Class Doc Comment
 *
 * @category    Class */
// * @description Riskv1authenticationresultsPaymentInformationFluidData
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Riskv1authenticationresultsPaymentInformationFluidDataTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Riskv1authenticationresultsPaymentInformationFluidData"
     */
    public function testRiskv1authenticationresultsPaymentInformationFluidData()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "keySerialNumber"
     */
    public function testPropertyKeySerialNumber()
    {
    }

    /**
     * Test attribute "descriptor"
     */
    public function testPropertyDescriptor()
    {
    }

    /**
     * Test attribute "encoding"
     */
    public function testPropertyEncoding()
    {
    }
}
