<?php
/**
 * Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentificationTest Class Doc Comment
 *
 * @category    Class */
// * @description Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentification
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentificationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Tmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentification"
     */
    public function testTmsv2customersEmbeddedDefaultPaymentInstrumentBuyerInformationPersonalIdentification()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "issuedBy"
     */
    public function testPropertyIssuedBy()
    {
    }
}
