<?php
/**
 * TssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * TssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description TssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformation"
     */
    public function testTssV2TransactionsPost201ResponseEmbeddedConsumerAuthenticationInformation()
    {
    }

    /**
     * Test attribute "xid"
     */
    public function testPropertyXid()
    {
    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "eciRaw"
     */
    public function testPropertyEciRaw()
    {
    }
}
