<?php
/**
 * TssV2TransactionsPost201ResponseEmbeddedOrderInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * TssV2TransactionsPost201ResponseEmbeddedOrderInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description TssV2TransactionsPost201ResponseEmbeddedOrderInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TssV2TransactionsPost201ResponseEmbeddedOrderInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TssV2TransactionsPost201ResponseEmbeddedOrderInformation"
     */
    public function testTssV2TransactionsPost201ResponseEmbeddedOrderInformation()
    {
    }

    /**
     * Test attribute "billTo"
     */
    public function testPropertyBillTo()
    {
    }

    /**
     * Test attribute "shipTo"
     */
    public function testPropertyShipTo()
    {
    }

    /**
     * Test attribute "amountDetails"
     */
    public function testPropertyAmountDetails()
    {
    }
}
