<?php
/**
 * Vasv2taxTaxInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CyberSource
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * CyberSource Merged Spec
 *
 * All CyberSource API specs merged together. These are available at https://developer.cybersource.com/api/reference/api-reference.html
 *
 * OpenAPI spec version: 0.0.1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Test\Model;

/**
 * Vasv2taxTaxInformationTest Class Doc Comment
 *
 * @category    Class */
// * @description Vasv2taxTaxInformation
/**
 * @package     CyberSource
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Vasv2taxTaxInformationTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Vasv2taxTaxInformation"
     */
    public function testVasv2taxTaxInformation()
    {
    }

    /**
     * Test attribute "reportingDate"
     */
    public function testPropertyReportingDate()
    {
    }

    /**
     * Test attribute "dateOverrideReason"
     */
    public function testPropertyDateOverrideReason()
    {
    }

    /**
     * Test attribute "nexus"
     */
    public function testPropertyNexus()
    {
    }

    /**
     * Test attribute "noNexus"
     */
    public function testPropertyNoNexus()
    {
    }

    /**
     * Test attribute "showTaxPerLineItem"
     */
    public function testPropertyShowTaxPerLineItem()
    {
    }

    /**
     * Test attribute "commitIndicator"
     */
    public function testPropertyCommitIndicator()
    {
    }

    /**
     * Test attribute "refundIndicator"
     */
    public function testPropertyRefundIndicator()
    {
    }
}
